### ISSUE TITLE
[Simulation] Wrong gravity without PID gains

### ISSUE THREAD

**Issue by achim-k** [ros-industrial/universal_robot#244]
When launching

``` bash
roslaunch ur_gazebo ur10.launch
```

with no fixed joint between `world` and `base_link` I noticed that the robot slowly floats down rather than directly falling on the ground (Note that I'm using Gazebo 6). When I switch to a velocity controller, the gravity is fine (see attached gifs).

What fixed it for me, was to specify pid gains for gazebo_ros_control, so that the control is done via [POSITION_PID](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/8ded7d387e3887707c485ef8a00514a57fd6381a/gazebo_ros_control/src/default_robot_hw_sim.cpp#L306) rather than [POSITION](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/8ded7d387e3887707c485ef8a00514a57fd6381a/gazebo_ros_control/src/default_robot_hw_sim.cpp#L298). The POSITION case uses [SetPosition(...)](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/8ded7d387e3887707c485ef8a00514a57fd6381a/gazebo_ros_control/src/default_robot_hw_sim.cpp#L300) for gazebo > 4 which apparently bypasses dynamics and just does a kinematic update of the joint value, which might have been the reason for the wrong gravity.

``` yaml
arm_controller:
  gains:
    shoulder_pan_joint: {p: 600.0, i: 500.0, d: 100.0, i_clamp: 100.0}
    shoulder_lift_joint: {p: 1500.0, i: 500.0, d: 100.0, i_clamp: 100.0}
    elbow_joint: {p: 1500.0, i: 500.0, d: 100.0, i_clamp: 100.0}
    wrist_1_joint: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 0.0}
    wrist_2_joint: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 0.0}
    wrist_3_joint: {p: 100.0, i: 0.0, d: 0.0, i_clamp: 0.0}
```

![position_control](https://cloud.githubusercontent.com/assets/9250155/15747695/3e63c4ac-28dc-11e6-873a-773a11eccc46.gif)

![velocity_control](https://cloud.githubusercontent.com/assets/9250155/15747700/4177bb62-28dc-11e6-8a7f-331a5099e2ef.gif)
