### ISSUE TITLE
Gazebo simulation not working

### ISSUE THREAD

**Issue by davizinho5** [ros-industrial/universal_robot#427]
Hello, 

I'm trying to use the universal packages in Ubuntu 18.04 and ROS-melodic. 

I installed the packages from source and downloaded all the dependencies manually. 

When I launched the Gazebo simulation, first it complained about not having control parameters in the PIDs. I solved it following the last comment in issue #397  , adding some gains. 

I don't see any error in the launch log, only the controller manager and spawner "finishing cleanly" make me make me doubt if this message is correct.  You can see it below:

`[ros_control_controller_manager-9] process has finished cleanly
log file: /home/amper/.ros/log/607db2d0-82e0-11e9-bdb8-f07bcb7ff7ac/ros_control_controller_manager-9*.log
Loaded 'arm_controller'
Loaded 'joint_state_controller'
Started ['arm_controller'] successfully
Started ['joint_state_controller'] successfully
[joint_state_controller_spawner-7] process has finished cleanly
log file: /home/amper/.ros/log/607db2d0-82e0-11e9-bdb8-f07bcb7ff7ac/joint_state_controller_spawner-7*.log
[arm_controller_spawner-8] process has finished cleanly
log file: /home/amper/.ros/log/607db2d0-82e0-11e9-bdb8-f07bcb7ff7ac/arm_controller_spawner-8*.log`

Then, the arm looks weird to me:
![arm](https://user-images.githubusercontent.com/8976895/58640798-1fe44800-82fa-11e9-9771-083465470809.png)

Finally, when I try to move it by commanding a trajectory, it looks like it tries to moves but it cannot:

````
rostopic pub /arm_controller/command trajectory_msgs/JointTrajectory "header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: ''
joint_names:
 ['shoulder_pan_joint', 'shoulder_lift_joint', 'elbow_joint', 'wrist_1_joint', 'wrist_2_joint', 'wrist_3_joint']
points:
- positions: [2,0,0,0,0,0]
  velocities: []
  accelerations: []
  effort: []
  time_from_start: {secs: 2, nsecs: 0}" 
````

Anyone knows why this happens? 
Could it be that the gains are not appropiate? How can I know when they are?
If it is because the controllers die, can you imagine why?

Best,
